// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import { IWorldID } from "./interfaces/IWorldID.sol";

/**
 * @title HumanVerifier
 * @notice Verifies unique human users via World ID and registers their wallet address.
 */
contract HumanVerifier {
    // The WorldID router instance
    IWorldID public immutable worldId;
    
    // Group ID 1 is for Orb-verified proofs
    uint256 public immutable groupId = 1;

    // The unique action identifier hash (external nullifier) configured for this gateway
    uint256 public immutable externalNullifier;

    // Mapping: walletAddress => isHuman (wallet registered to a verified human)
    mapping(address => bool) public isHuman;

    // Mapping: nullifierHash => hasRegistered (ensures a human identity is only used once)
    mapping(uint256 => bool) public nullifierHashes;

    event HumanRegistered(address indexed user, uint256 indexed nullifierHash);

    constructor(IWorldID _worldId, uint256 _externalNullifier) {
        worldId = _worldId;
        externalNullifier = _externalNullifier;
    }

    /**
     * @notice Registers the calling wallet address as a verified human.
     * @param root The Merkle root of the World ID tree.
     * @param nullifierHash The unique identifier for this human and action.
     * @param proof The ZK-proof generated by World ID.
     */
    function registerHuman(
        uint256 root,
        uint256 nullifierHash,
        uint256[8] calldata proof
    ) external {
        // 1. Ensure this wallet address isn't already registered
        require(!isHuman[msg.sender], "Address already registered");

        // 2. Ensure this specific human identity hasn't been registered yet (Sybil protection)
        require(!nullifierHashes[nullifierHash], "Identity already registered");

        // 3. The signal is the address of the msg.sender (to bind proof to caller)
        // Hash it and truncate to fit the Semaphore field
        uint256 signalHash = uint256(keccak256(abi.encodePacked(msg.sender))) >> 8;

        // 4. Verify ZK Proof via World ID router (reverts if invalid)
        worldId.verifyProof(
            root,
            groupId,
            signalHash,
            nullifierHash,
            externalNullifier,
            proof
        );

        // 5. Save registration state
        nullifierHashes[nullifierHash] = true;
        isHuman[msg.sender] = true;

        emit HumanRegistered(msg.sender, nullifierHash);
    }
}
